  minecraft:
    # Docker Config
    image: "itzg/minecraft-server:{{WORLD_INSTANCE_IMAGE_VERSION}}"
    tty: true
    stdin_open: true
    network_mode: "host"
    volumes:
      - "./instances/{{WORLD_INSTANCE_DIR}}:/data"
      - "./modpacks:/modpacks:ro"
      - "./_mc_hist.txt:/history.txt"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mc-health"]
      start_period: 210s #3,5min
      interval: 3s
      retries: 40 #extra 2min
    secrets:
      - db_host
      - db_port
      - db_name
      - db_user
      - db_password
      - db_table_accounts_ingame
      - bot_poltergeist
      - seed
    depends_on:
      db:
        condition: service_started
    post_start:
      - command: "sh -c 'date >> /history.txt; echo \"$$LAUNCHED_WITH_DIGEST\" >> /history.txt'"
    # MC Config
    environment:
      # Modpack
      TYPE: "MODRINTH"
      MODRINTH_MODPACK: "{{WORLD_INSTANCE_MODPACK}}"
      # Minecraft stuff
      GUI: "FALSE"
      EULA: "TRUE"              #  Why are some bools upper-case...
      # Java stuff
      MEMORY: "{{RAM_ALLOCATION}}G"
      USE_AIKAR_FLAGS: "true"   #  ...and others lower-case? No fucking idea! I'm just following the docs, that's all.
      # Secrets
      CFG_DB_HOST_FILE: "/run/secrets/db_host"
      CFG_DB_PORT_FILE: "/run/secrets/db_port"
      CFG_DB_NAME_FILE: "/run/secrets/db_name"
      CFG_DB_TABLE_FILE: "/run/secrets/db_table_accounts_ingame"
      CFG_DB_USER_FILE: "/run/secrets/db_user"
      CFG_DB_PASS_FILE: "/run/secrets/db_password"
      CFG_BOT_TOKEN_FILE: "/run/secrets/bot_poltergeist"
      CFG_SEED_FILE: "/run/secrets/seed"
      # Desperately trying to get Secrets to work
      REPLACE_ENV_VARIABLES: "TRUE"
      ENV_VARIABLE_PREFIX: "CFG_"
      REPLACE_ENV_IN_PLACE: "true"
      REPLACE_ENV_DURING_SYNC: "true"
      # Misc
      #UID: "42069"
      #GID: "121"
      TZ: "Europe/Warsaw"
      LOG_TIMESTAMP: "true"
      LEVEL: "{{WORLD_NAME_INNER}}"
      DATAPACKS: "datapacks/"
      LAUNCHED_WITH_DIGEST: "{{DIGEST}}"
  
  backuper:
    image: itzg/mc-backup
    #user: "42069"
    depends_on:
      minecraft:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "10h"
      RCON_HOST: "minecraft"
      INITIAL_DELAY: 0
      EXCLUDES: ".cache,.fabric,.fabric-manifest.json,.install-modrinth.env,.local,.mixin.out,.modrinth-modpack-manifest.json,.rcon-cli.env,.rcon-cli.yaml,config,crash-reports,credits.txt,debug,defaultconfigs,eula.txt,*.jar,*.log,icon.png,immersive_paintings_cache,kiwipacks,libraries,locale_cache,logs,modernfix,mods,observable_announce,patchouli_books,server-icon.png,server.properties,shaderpacks,usercache.json,usernamecache.json,versions,wrld_minimal_backup.zip"
      TZ: "Europe/Warsaw"
      BACKUP_NAME: "full"
      PRUNE_BACKUPS_DAYS: 3
    volumes:
      - ./instances/{{WORLD_INSTANCE_DIR}}:/data:ro
      - ./backups/{{WORLD_NAME}}:/backups